// ********RoostGPT********
/*
Test generated by RoostGPT for test Go-lang12345 using AI Type Claude AI and AI Model claude-3-5-sonnet-20241022

ROOST_METHOD_HASH=Comment.ProtoComment_2ec41d63f7
ROOST_METHOD_SIG_HASH=Comment.ProtoComment_fcb2b2ac3a

FUNCTION_DEF=func (c *Comment) ProtoComment() *pb.Comment // ProtoComment generates proto comment model from article

Scenario 1: Valid Comment Conversion to Proto Format

Details:
  Description: Tests the successful conversion of a standard Comment struct to its protocol buffer representation with all fields populated correctly.

Execution:
  Arrange:
    - Create a Comment struct with valid ID, Body, CreatedAt, and UpdatedAt fields
    - Set up expected timestamp format in ISO8601
  Act:
    - Call ProtoComment() on the created Comment instance
  Assert:
    - Verify ID is correctly converted to string format
    - Verify Body matches the original content
    - Verify CreatedAt and UpdatedAt are formatted according to ISO8601
    - Verify the returned proto.Comment structure matches expectations

Validation:
  This test ensures the basic functionality of converting a model Comment to its proto representation, which is crucial for API responses and data transmission.

*/

// ********RoostGPT********

package model

import (
	"testing"
	"time"

	"github.com/jinzhu/gorm"
	pb "github.com/raahii/golang-grpc-realworld-example/proto"
	"github.com/stretchr/testify/assert"
)

func TestCommentProtoComment(t *testing.T) {

	now := time.Now()

	tests := []struct {
		name     string
		comment  Comment
		expected *pb.Comment
	}{
		{
			name: "Valid comment conversion to proto format",
			comment: Comment{
				Model: gorm.Model{
					ID:        1,
					CreatedAt: now,
					UpdatedAt: now,
				},
				Body:      "Test comment body",
				UserID:    1,
				Author:    User{},
				ArticleID: 1,
				Article:   Article{},
			},
			expected: &pb.Comment{
				Id:        "1",
				Body:      "Test comment body",
				CreatedAt: now.Format(ISO8601),
				UpdatedAt: now.Format(ISO8601),
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := tt.comment.ProtoComment()
			assert.Equal(t, tt.expected.Id, got.Id)
			assert.Equal(t, tt.expected.Body, got.Body)
			assert.Equal(t, tt.expected.CreatedAt, got.CreatedAt)
			assert.Equal(t, tt.expected.UpdatedAt, got.UpdatedAt)
		})
	}
}
