# ********RoostGPT********

# Test generated by RoostGPT for test amanKarate11thJUly using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /kafka/v3/clusters/{cluster_id}/topics/{topic_name}/partitions/{partition_id}_get for http method type GET 
# RoostTestHash=0ecd20dc17
# 
# 

# ********RoostGPT********
Feature: Kafka Partition API Tests

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Accept: 'application/json' }

  Scenario Outline: Get Partition with Basic Authentication
    Given path 'kafka/v3/clusters', <cluster_id>, 'topics', <topic_name>, 'partitions', <partition_id>
    And def username = karate.properties['BASIC_USERNAME']
    And def password = karate.properties['BASIC_PASSWORD']
    And def credentials = username + ':' + password
    And def encoded = Java.type('java.util.Base64').getEncoder().encodeToString(credentials.getBytes())
    And def authHeader = 'Basic ' + encoded
    * configure headers = { Authorization: '#(authHeader)' }
    When method GET
    Then status 200
    And match response.kind == 'KafkaPartition'
    And match response.metadata.self == urlBase + '/kafka/v3/clusters/' + <cluster_id> + '/topics/' + <topic_name> + '/partitions/' + <partition_id>
    And match response.metadata.resource_name == '#string'
    And match response.cluster_id == <cluster_id>
    And match response.topic_name == <topic_name>
    And match response.partition_id == <partition_id>
    And match response.leader.related == '#string'
    And match response.replicas.related == '#string'
    And match response.reassignment.related == '#string'

    Examples:
      | read('kafka_v3_clusters_cluster_id_topics_topic_name_partitions_partition_id_get.csv') |

  Scenario Outline: Get Partition with OAuth2 Authentication
    Given path 'kafka/v3/clusters', <cluster_id>, 'topics', <topic_name>, 'partitions', <partition_id>
    And def authToken = 'Bearer ' + karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)' }
    When method GET
    Then status 200
    And match response.kind == 'KafkaPartition'
    And match response.metadata.self == urlBase + '/kafka/v3/clusters/' + <cluster_id> + '/topics/' + <topic_name> + '/partitions/' + <partition_id>
    And match response.metadata.resource_name == '#string'
    And match response.cluster_id == <cluster_id>
    And match response.topic_name == <topic_name>
    And match response.partition_id == <partition_id>
    And match response.leader.related == '#string'
    And match response.replicas.related == '#string'
    And match response.reassignment.related == '#string'

    Examples:
      | read('kafka_v3_clusters_cluster_id_topics_topic_name_partitions_partition_id_get.csv') |

  Scenario: Get Partition with Invalid Cluster ID
    Given path 'kafka/v3/clusters', 'invalid-cluster', 'topics', 'topic-1', 'partitions', 1
    And def authToken = 'Bearer ' + karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)' }
    When method GET
    Then status 404
    And match response.error_code == 404
    And match response.message == '##string'

  Scenario: Get Partition with Invalid Topic Name
    Given path 'kafka/v3/clusters', 'cluster-1', 'topics', 'invalid-topic', 'partitions', 1
    And def authToken = 'Bearer ' + karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)' }
    When method GET
    Then status 404
    And match response.error_code == 404
    And match response.message == '##string'

  Scenario: Get Partition with Invalid Partition ID
    Given path 'kafka/v3/clusters', 'cluster-1', 'topics', 'topic-1', 'partitions', 999
    And def authToken = 'Bearer ' + karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)' }
    When method GET
    Then status 404
    And match response.error_code == 404
    And match response.message == '##string'

  Scenario: Get Partition with Missing Authentication
    Given path 'kafka/v3/clusters', 'cluster-1', 'topics', 'topic-1', 'partitions', 1
    When method GET
    Then status 401
    And match response.error_code == 40101
    And match response.message == '##string'

  Scenario: Get Partition with Authorization Error
    Given path 'kafka/v3/clusters', 'cluster-1', 'topics', 'topic-1', 'partitions', 1
    And def authToken = 'Bearer ' + 'invalid_token'
    * configure headers = { Authorization: '#(authToken)' }
    When method GET
    Then status 403
    And match response.error_code == 40301
    And match response.message == '##string'

  Scenario: Get Partition Rate Limit Exceeded
    Given path 'kafka/v3/clusters', 'cluster-1', 'topics', 'topic-1', 'partitions', 1
    And def authToken = 'Bearer ' + karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)' }
    When method GET
    Then status 429
