# ********RoostGPT********

# Test generated by RoostGPT for test amanKarate11thJUly using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /kafka/v3/clusters/{cluster_id}/topics/{topic_name}_delete for http method type DELETE 
# RoostTestHash=b9526a5d59
# 
# 

# ********RoostGPT********
Feature: Kafka Topic Management

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Accept: 'application/json' }

  Scenario Outline: Delete Kafka Topic with Basic Authentication
    Given path 'kafka/v3/clusters/<cluster_id>/topics/<topic_name>'
    * def username = karate.properties['BASIC_USERNAME']
    * def password = karate.properties['BASIC_PASSWORD']
    * def credentials = username + ':' + password
    * def encoded = Java.type('java.util.Base64').getEncoder().encodeToString(credentials.getBytes())
    * def authHeader = 'Basic ' + encoded
    * configure headers = { Authorization: '#(authHeader)' }
    When method DELETE
    Then status 204

    Examples:
      | read('kafka_v3_clusters_cluster_id_topics_topic_name_delete.csv') |

  Scenario Outline: Delete Kafka Topic with OAuth2 Authentication
    Given path 'kafka/v3/clusters/<cluster_id>/topics/<topic_name>'
    * def authToken = karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)' }
    When method DELETE
    Then status 204

    Examples:
      | read('kafka_v3_clusters_cluster_id_topics_topic_name_delete.csv') |

  Scenario Outline: Delete Kafka Topic with Bad Request Error
    Given path 'kafka/v3/clusters/<cluster_id>/topics/<topic_name>'
    * def authToken = karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)' }
    When method DELETE
    Then status 400
    And match response.error_code == 400
    And match response.message == '##string'

    Examples:
      | cluster_id        | topic_name      |
      | 'invalid-cluster' | 'invalid-topic' |

  Scenario: Delete Kafka Topic Unauthorized Error
    Given path 'kafka/v3/clusters/cluster-1/topics/topic-1'
    * def authHeader = 'Basic ' + 'invalid_credentials'
    * configure headers = { Authorization: '#(authHeader)' }
    When method DELETE
    Then status 401
    And match response.error_code == 40101
    And match response.message == '##string'

  Scenario: Delete Kafka Topic Forbidden Error
    Given path 'kafka/v3/clusters/cluster-1/topics/topic-1'
    * def authToken = karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)' }
    When method DELETE
    Then status 403
    And match response.error_code == 40301
    And match response.message == '##string'

  Scenario: Delete Kafka Topic Not Found Error
    Given path 'kafka/v3/clusters/non-existing-cluster/topics/non-existing-topic'
    * def authToken = karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)' }
    When method DELETE
    Then status 404
    And match response.error_code == 404
    And match response.message == '##string'

  Scenario: Delete Kafka Topic Rate Limit Error
    Given path 'kafka/v3/clusters/cluster-1/topics/topic-1'
    * def authToken = karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)' }
    When method DELETE
    Then status 429
    And match response == '#string'

  Scenario: Delete Kafka Topic Internal Server Error
    Given path 'kafka/v3/clusters/cluster-1/topics/topic-1'
    * def authToken = karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)' }
    When method DELETE
    Then status 500
    And match response.error_code == 500
    And match response.message == '##string'
