// ********RoostGPT********
/*
Test generated by RoostGPT for test gosep using AI Type Open AI and AI Model gpt-4o

ROOST_METHOD_HASH=Handler.DeleteArticle_ebf158c2cf
ROOST_METHOD_SIG_HASH=Handler.DeleteArticle_2f9fc6e09e

FUNCTION_DEF=func (h *Handler) DeleteArticle(ctx context.Context, req *pb.DeleteArticleRequest) (*pb.Empty, error) // DeleteArticle deletes an article

Existing Test Information:
These test cases are already implemented and not included for test generation scenario:
File: golang-grpc-realworld-example/handler/article_test.go
Test Cases:
    [TestDeleteArticle]

Scenario 1: Unauthenticated User Attempting to Delete an Article

Details:
  Description: This test checks the behavior of the DeleteArticle function when an unauthenticated user attempts to delete an article. The function should return an error indicating that the user is unauthenticated.
Execution:
  Arrange: Set up a context without authentication credentials and prepare a DeleteArticleRequest with a valid article slug.
  Act: Invoke the DeleteArticle function with the unauthenticated context and the request.
  Assert: Verify that the function returns an error with the code Unauthenticated.
Validation:
  Explain the choice of assertion and the logic behind the expected result: The assertion checks for an Unauthenticated error, which is expected because the user is not logged in. This test is important to ensure that only authenticated users can perform actions that modify data.

Scenario 2: Valid Token but User Not Found in Database

Details:
  Description: This test verifies the function's response when a valid token is provided, but the corresponding user does not exist in the database. The function should return a NotFound error.
Execution:
  Arrange: Generate a valid token for a non-existent user ID and set up the context with this token. Prepare a DeleteArticleRequest with a valid article slug.
  Act: Call the DeleteArticle function with the context and request.
  Assert: Check that the function returns a NotFound error.
Validation:
  Explain the choice of assertion and the logic behind the expected result: The assertion ensures that the function correctly identifies when a user does not exist, even if the token is valid. This test is crucial for maintaining data integrity and preventing unauthorized access.

Scenario 3: Invalid Article Slug Conversion

Details:
  Description: This test examines the function's behavior when the article slug cannot be converted to an integer. The function should return an InvalidArgument error.
Execution:
  Arrange: Create a DeleteArticleRequest with a non-numeric slug and set up a valid authenticated context.
  Act: Invoke the DeleteArticle function with the context and request.
  Assert: Verify that the function returns an InvalidArgument error.
Validation:
  Explain the choice of assertion and the logic behind the expected result: The assertion checks for an InvalidArgument error, which is expected when the slug is not a valid integer. This test is important to ensure that the function handles input validation correctly.

Scenario 4: Article Not Found by ID

Details:
  Description: This test checks the function's response when the article ID derived from the slug does not exist in the database. The function should return an InvalidArgument error.
Execution:
  Arrange: Set up a valid authenticated context and prepare a DeleteArticleRequest with a slug corresponding to a non-existent article ID.
  Act: Call the DeleteArticle function with the context and request.
  Assert: Verify that the function returns an InvalidArgument error.
Validation:
  Explain the choice of assertion and the logic behind the expected result: The assertion ensures that the function correctly handles cases where the article does not exist. This test is important for preventing operations on non-existent data.

Scenario 5: User Attempting to Delete Another User's Article

Details:
  Description: This test verifies the function's behavior when a user attempts to delete an article authored by another user. The function should return a Forbidden error.
Execution:
  Arrange: Set up a valid authenticated context for a user and prepare a DeleteArticleRequest with a slug for an article authored by a different user.
  Act: Invoke the DeleteArticle function with the context and request.
  Assert: Check that the function returns a Forbidden error.
Validation:
  Explain the choice of assertion and the logic behind the expected result: The assertion checks for a Forbidden error, which is expected when a user tries to delete another user's article. This test is crucial for enforcing access control and protecting user data.

Scenario 6: Successful Article Deletion

Details:
  Description: This test confirms the successful deletion of an article by its author. The function should return a successful response with no errors.
Execution:
  Arrange: Set up a valid authenticated context for the article's author and prepare a DeleteArticleRequest with the correct article slug.
  Act: Call the DeleteArticle function with the context and request.
  Assert: Verify that the function returns a successful response with no errors.
Validation:
  Explain the choice of assertion and the logic behind the expected result: The assertion ensures that the function performs the deletion correctly when all conditions are met. This test is important for verifying the core functionality of the article deletion feature.

*/

// ********RoostGPT********

package handler

import (
	"context"
	"fmt"
	"testing"

	"github.com/raahii/golang-grpc-realworld-example/auth"
	"github.com/raahii/golang-grpc-realworld-example/model"
	"github.com/raahii/golang-grpc-realworld-example/proto"
	"github.com/raahii/golang-grpc-realworld-example/store"
	"github.com/rs/zerolog"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

type MockWriter struct{}

func (m *MockWriter) Write(p []byte) (n int, err error) {
	return len(p), nil
}
func TestHandlerDeleteArticle(t *testing.T) {
	logger := zerolog.New(zerolog.ConsoleWriter{Out: &MockWriter{}})
	us := &store.UserStore{}
	as := &store.ArticleStore{}
	h := &Handler{logger: &logger, us: us, as: as}

	fooUser := model.User{ID: 1, Username: "foo", Email: "foo@example.com", Password: "secret"}
	barUser := model.User{ID: 2, Username: "bar", Email: "bar@example.com", Password: "secret"}
	article := model.Article{ID: 1, Title: "original title", Description: "original desc", Body: "original body", Author: fooUser, Tags: []model.Tag{{Name: "hoge"}}}

	tests := []struct {
		title    string
		setup    func() context.Context
		req      *proto.DeleteArticleRequest
		expected codes.Code
	}{
		{
			title: "Unauthenticated User Attempting to Delete an Article",
			setup: func() context.Context {
				return context.Background()
			},
			req:      &proto.DeleteArticleRequest{Slug: fmt.Sprintf("%d", article.ID)},
			expected: codes.Unauthenticated,
		},
		{
			title: "Valid Token but User Not Found in Database",
			setup: func() context.Context {
				token, _ := auth.GenerateToken(999)
				return ctxWithToken(context.Background(), token)
			},
			req:      &proto.DeleteArticleRequest{Slug: fmt.Sprintf("%d", article.ID)},
			expected: codes.NotFound,
		},
		{
			title: "Invalid Article Slug Conversion",
			setup: func() context.Context {
				token, _ := auth.GenerateToken(fooUser.ID)
				return ctxWithToken(context.Background(), token)
			},
			req:      &proto.DeleteArticleRequest{Slug: "invalid-slug"},
			expected: codes.InvalidArgument,
		},
		{
			title: "Article Not Found by ID",
			setup: func() context.Context {
				token, _ := auth.GenerateToken(fooUser.ID)
				return ctxWithToken(context.Background(), token)
			},
			req:      &proto.DeleteArticleRequest{Slug: "999"},
			expected: codes.InvalidArgument,
		},
		{
			title: "User Attempting to Delete Another User's Article",
			setup: func() context.Context {
				token, _ := auth.GenerateToken(barUser.ID)
				return ctxWithToken(context.Background(), token)
			},
			req:      &proto.DeleteArticleRequest{Slug: fmt.Sprintf("%d", article.ID)},
			expected: codes.Unauthenticated,
		},
		{
			title: "Successful Article Deletion",
			setup: func() context.Context {
				token, _ := auth.GenerateToken(fooUser.ID)
				return ctxWithToken(context.Background(), token)
			},
			req:      &proto.DeleteArticleRequest{Slug: fmt.Sprintf("%d", article.ID)},
			expected: codes.OK,
		},
	}

	for _, tt := range tests {
		t.Run(tt.title, func(t *testing.T) {
			ctx := tt.setup()
			_, err := h.DeleteArticle(ctx, tt.req)
			if status.Code(err) != tt.expected {
				t.Errorf("expected error code %v, got %v", tt.expected, status.Code(err))
			}
		})
	}
}
